spring: 
    profiles: 
    active: 
    -dev
---
spring: 
    profiles: dev
    application: 
        name: microservicecloud-config-itliuyue-dev
---
spring: 
    profiles: test
    application: 
        name: microservicecloud-config-itliuyue-test